//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public Nullable<bool> isDiabetes { get; set; }
        public Nullable<bool> isCholesterol { get; set; }
        public string heart_disease { get; set; }
        public Nullable<bool> isObesity { get; set; }
        public Nullable<bool> isExercise { get; set; }
        public string exerciseOften { get; set; }
        public string dateExercise { get; set; }
        public Nullable<bool> isDrug { get; set; }
        public string nameDrug { get; set; }
        public Nullable<bool> isSmoking { get; set; }
        public string oftenSmoke { get; set; }
        public string brandSmoke { get; set; }
        public string amountTypeSmoke { get; set; }
        public string amountSmoke { get; set; }
        public string painLevel { get; set; }
        public string feeling { get; set; }
        public string bloodPressure { get; set; }
        public string trauma { get; set; }
        public string vomitAmount { get; set; }
        public string feverDgree { get; set; }
        public string painLocation { get; set; }
        public string timeOfPain { get; set; }
        public string havaFever { get; set; }
        public string disease { get; set; }
    }
}
