//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public bool isDiabetes { get; set; }
        public bool isCholesterol { get; set; }
        public string heart_disease { get; set; }
        public bool isObesity { get; set; }
        public bool isExercise { get; set; }
        public string exerciseOften { get; set; }
        public string dateExercise { get; set; }
        public bool isDrug { get; set; }
        public string nameDrug { get; set; }
        public bool isSmoking { get; set; }
        public string oftenSmoke { get; set; }
        public string brandSmoke { get; set; }
        public string amountTypeSmoke { get; set; }
        public string amountSmoke { get; set; }
    }
}
