//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogFlowWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {




        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public string isDiabetes { get; set; }
        public string isCholesterol { get; set; }
        public string heart_disease { get; set; }
        public string isObesity { get; set; }
        public string isExercise { get; set; }
        public string exerciseOften { get; set; }
        public string dateExercise { get; set; }
        public string isDrug { get; set; }
        public string nameDrug { get; set; }
        public string isSmoking { get; set; }
        public string oftenSmoke { get; set; }
        public string brandSmoke { get; set; }
        public string amountTypeSmoke { get; set; }
        public string amountSmoke { get; set; }
    }
}
